# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://sofiag1l.github.io/'
baseurl: ''
title: 'Sofia Gil-Clavel'
description: 'PhD Student at the Max Planck Institute for Demographic Research'
permalink: pretty
logo: "/logos/logo.svg" # Site logo, also used in jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: CV
  url: /Files/SofiaGil_EnglishCV.pdf
- title: About
  url: /about/
- title: Events
  url: /blog/
- title: Github
  url: https://github.com/SofiaG1l
  

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
