# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://sofiag1l.github.io/'
baseurl: ''
title: 'Sofia Gil-Clavel'
description: 'Post Doctoral Researcher at TU Delft'
permalink: pretty
logo: "/logos/logo.svg" # Site logo, also used in jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: CVs
  url: /CVs/
- title: Publications
  url: /about/
- title: Collections
  url: /categories/
- title: Contact
  url: /contact/
- title: Github
  url: https://github.com/SofiaG1l
  

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Collections
    output: true
    description: "Here you can find more about me."
    feature_image: "https://i.picsum.photos/id/7/4728/3168.jpg"
